# backend/app/models/notification.py

from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey
from sqlalchemy.sql import func

from app.database import Base

class Notification(Base):
    """
    SQLAlchemy model representing system and administrative notifications.

    Tracks audit trails and real-time alerts generated by user lifecycle events, 
    including advanced state tracking for concurrent administrators.

    Attributes:
        id (int): Primary key and indexed identifier for the notification.
        type (str): Categorization type of the notification (e.g., "user_registration"). Defaults to "user_registration".
        message (str): The descriptive text body of the notification alert.
        related_user_id (int, optional): Foreign key linking to the User who triggered or is the subject of the notification.
        acted_by_admin_id (int, optional): Foreign key linking to the User (Admin) who acted upon a notification.
        is_read (bool): General global flag indicating if the notification has been read. Defaults to False.
        created_at (datetime): Timezone-aware timestamp indicating when the notification was emitted.
    """
    __tablename__ = "notifications"

    # Core identification fields
    id = Column(Integer, primary_key=True, index=True)
    type = Column(String, nullable=False, default="user_registration")
    message = Column(String, nullable=False)
    
    # Relational tracking fields
    # References the primary target user involved in the event notification context
    related_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # For status_change notifications: tracks the specific admin who performed the action.
    # Used to mark the notification as already-read for that admin while
    # keeping it unread for all other concurrent admins.
    acted_by_admin_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # Read state management
    is_read = Column(Boolean, nullable=False, default=False)
    
    # Audit logging timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())