import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export interface PDFExportOptions {
  title: string;
  district: string;
  dateStr: string;
  filters: string[];
}

export class PdfEngine {
  private doc: jsPDF;
  private pageWidth: number;
  private pageHeight: number;
  private margin: number = 15;
  private currentY: number = 15;

  constructor() {
    this.doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });
    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.pageHeight = this.doc.internal.pageSize.getHeight();
  }

  /**
   * Adds the cover page to the document.
   */
  public addCoverPage(options: PDFExportOptions) {
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(24);
    this.doc.setTextColor(30, 58, 138); // #1e3a8a
    
    const titleLines = this.doc.splitTextToSize("Government Road Accident Analysis Report", this.pageWidth - 2 * this.margin);
    let y = 60;
    this.doc.text(titleLines, this.pageWidth / 2, y, { align: "center" });
    
    y += titleLines.length * 10 + 10;
    this.doc.setFontSize(16);
    this.doc.setTextColor(100, 100, 100);
    this.doc.text("G-TRISP Dashboard", this.pageWidth / 2, y, { align: "center" });
    
    y += 20;
    this.doc.setFontSize(14);
    this.doc.setTextColor(50, 50, 50);
    this.doc.text(`District: ${options.district}`, this.pageWidth / 2, y, { align: "center" });
    
    y += 10;
    this.doc.text(`Generated: ${options.dateStr}`, this.pageWidth / 2, y, { align: "center" });
    
    y += 30;
    this.doc.setFontSize(12);
    this.doc.setFont("helvetica", "bold");
    this.doc.text("Applied Filters:", this.pageWidth / 2, y, { align: "center" });
    
    y += 10;
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(10);
    
    if (options.filters.length === 0) {
      this.doc.text("All (No filters applied)", this.pageWidth / 2, y, { align: "center" });
    } else {
      options.filters.forEach(f => {
        this.doc.text(f, this.pageWidth / 2, y, { align: "center" });
        y += 6;
      });
    }

    // Logo placeholder
    this.doc.setDrawColor(200, 200, 200);
    this.doc.setFillColor(240, 240, 240);
    this.doc.rect(this.pageWidth / 2 - 25, 20, 50, 20, "F");
    this.doc.rect(this.pageWidth / 2 - 25, 20, 50, 20, "S");
    this.doc.setFontSize(10);
    this.doc.setTextColor(150, 150, 150);
    this.doc.text("G-TRISP Logo", this.pageWidth / 2, 32, { align: "center" });
    
    this.addFooter();
  }

  /**
   * Adds a new page with a standard header.
   */
  public addNewPage(sectionTitle: string) {
    this.doc.addPage();
    this.currentY = this.margin;
    
    // Header
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(14);
    this.doc.setTextColor(30, 58, 138);
    this.doc.text(sectionTitle, this.margin, this.currentY);
    
    this.doc.setDrawColor(220, 220, 220);
    this.doc.line(this.margin, this.currentY + 2, this.pageWidth - this.margin, this.currentY + 2);
    
    this.currentY += 15;
    this.addFooter();
  }

  public addHeader(text: string) {
      this.doc.setFont("helvetica", "bold");
      this.doc.setFontSize(12);
      this.doc.setTextColor(50, 50, 50);
      this.doc.text(text, this.margin, this.currentY);
      this.currentY += 8;
  }

  /**
   * Captures an HTML element and adds it to the PDF.
   * Auto-scales and adds page breaks if necessary.
   */
  public async addElementAsImage(elementId: string, title?: string) {
    const el = document.getElementById(elementId);
    if (!el) {
        console.warn(`Element with ID ${elementId} not found.`);
        return;
    }

    // Capture the element
    const canvas = await html2canvas(el, { 
        scale: 2, 
        useCORS: true, 
        backgroundColor: "#ffffff",
        logging: false
    });
    const imgData = canvas.toDataURL("image/png");
    
    const imgWidth = this.pageWidth - 2 * this.margin;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    // Check if we need a new page
    if (title) {
        if (this.currentY + imgHeight + 15 > this.pageHeight - this.margin - 10) {
            this.addNewPage("Continued...");
        }
        this.addHeader(title);
    } else if (this.currentY + imgHeight > this.pageHeight - this.margin - 10) {
        this.addNewPage("Continued...");
    }

    this.doc.addImage(imgData, "PNG", this.margin, this.currentY, imgWidth, imgHeight);
    this.currentY += imgHeight + 10;
  }

  private addFooter() {
    const pageCount = this.doc.getNumberOfPages();
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(8);
    this.doc.setTextColor(150, 150, 150);
    this.doc.text(`Page ${pageCount}`, this.pageWidth / 2, this.pageHeight - 10, { align: "center" });
    this.doc.text("Generated by G-TRISP Dashboard", this.margin, this.pageHeight - 10);
  }

  public save(filename: string) {
    this.doc.save(filename);
  }
}
